# Generated by Django 2.2 on 2020-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='description',
            field=models.TextField(default='old dojo'),
        ),
    ]
